"""auto update

Revision ID: 64793e912afe
Revises: 1039947bff03
Create Date: 2026-01-30 05:46:02.270970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64793e912afe'
down_revision: Union[str, Sequence[str], None] = '1039947bff03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experience_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('experience_change', sa.Integer(), nullable=True),
    sa.Column('points_change', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experience_logs_id'), 'experience_logs', ['id'], unique=False)
    op.create_table('inspectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('appointed_at', sa.String(), nullable=True),
    sa.Column('appointed_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspectors_id'), 'inspectors', ['id'], unique=False)
    op.create_table('order_logistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(), nullable=True),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_location', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_logistics_id'), 'order_logistics', ['id'], unique=False)
    op.create_table('post_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_reviews_id'), 'post_reviews', ['id'], unique=False)
    op.create_table('posts_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('post_type', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('review_status', sa.String(), server_default='approved', nullable=True),
    sa.Column('reward_points', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_solved', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('solver_id', sa.String(), nullable=True),
    sa.Column('likes_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('comments_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_v2_id'), 'posts_v2', ['id'], unique=False)
    op.create_table('product_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_ratings_id'), 'product_ratings', ['id'], unique=False)
    op.create_table('review_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_id'), 'review_tasks', ['id'], unique=False)
    op.create_table('shop_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_ratings_id'), 'shop_ratings', ['id'], unique=False)
    op.create_table('shop_reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('review_comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_reviews_id'), 'shop_reviews', ['id'], unique=False)
    op.create_table('shops_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default='pending', nullable=True),
    sa.Column('average_rating', sa.Float(), server_default='0', nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_v2_id'), 'shops_v2', ['id'], unique=False)
    op.create_table('users_extended',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('experience', sa.Integer(), server_default='0', nullable=True),
    sa.Column('level', sa.Integer(), server_default='1', nullable=True),
    sa.Column('points', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_extended_id'), 'users_extended', ['id'], unique=False)
    op.alter_column('products', 'shop_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('products', 'shop_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_extended_id'), table_name='users_extended')
    op.drop_table('users_extended')
    op.drop_index(op.f('ix_shops_v2_id'), table_name='shops_v2')
    op.drop_table('shops_v2')
    op.drop_index(op.f('ix_shop_reviews_id'), table_name='shop_reviews')
    op.drop_table('shop_reviews')
    op.drop_index(op.f('ix_shop_ratings_id'), table_name='shop_ratings')
    op.drop_table('shop_ratings')
    op.drop_index(op.f('ix_review_tasks_id'), table_name='review_tasks')
    op.drop_table('review_tasks')
    op.drop_index(op.f('ix_product_ratings_id'), table_name='product_ratings')
    op.drop_table('product_ratings')
    op.drop_index(op.f('ix_posts_v2_id'), table_name='posts_v2')
    op.drop_table('posts_v2')
    op.drop_index(op.f('ix_post_reviews_id'), table_name='post_reviews')
    op.drop_table('post_reviews')
    op.drop_index(op.f('ix_order_logistics_id'), table_name='order_logistics')
    op.drop_table('order_logistics')
    op.drop_index(op.f('ix_inspectors_id'), table_name='inspectors')
    op.drop_table('inspectors')
    op.drop_index(op.f('ix_experience_logs_id'), table_name='experience_logs')
    op.drop_table('experience_logs')
    # ### end Alembic commands ###